"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var app_1 = require("./src/app");
var numberGroup_1 = require("./src/model/numberGroup");
var characterGroup_1 = require("./src/model/characterGroup");
var LinkedListGroup_1 = require("./src/model/LinkedListGroup");
var numberGroup = new numberGroup_1.NumberGroup([30, 3, -15, 0]);
var sorter1 = new app_1.SortUtil(numberGroup);
sorter1.sort();
console.log(numberGroup.data);
console.log("-----------------");
var characterGroup = new characterGroup_1.CharacterGroup("Xaeyb");
var sorter2 = new app_1.SortUtil(characterGroup);
sorter2.sort();
console.log(characterGroup.data);
console.log("------------------");
var linkedListGroup = new LinkedListGroup_1.LinkedListGroup();
linkedListGroup.add(520);
linkedListGroup.add(-10);
linkedListGroup.add(-7);
linkedListGroup.add(4);
var sorter3 = new app_1.SortUtil(linkedListGroup);
sorter3.sort();
linkedListGroup.print();
